name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        npm-version: '9.8.1'
        cache: 'npm'
        cache-dependency-path: library/package-lock.json
    
    # Run npm commands in the 'library' directory
    - name: Install dependencies
      run: npm ci
      working-directory: library

    - name: Build
      run: npm run build
      working-directory: library

    - name: List contents of the library directory after build
      run: ls -la
      working-directory: library

    - name: Run tests
      run: npm test
      working-directory: library

    - name: Debugging before deploy
      run: pwd && ls -la
      working-directory: library

    - name: Deploy with gh-pages
      run: npm run deploy
      working-directory: library
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
